server:
  port: 8083

  tomcat:
    uri-encoding: utf-8

  servlet:
    session:
      timeout: 30m

spring:

  application:
    name: mongodb

  profiles:
    active: dev

  data:
    mongodb:
      database: admin
      host: 127.0.0.1
      port: 27017
      username: root
      password: root