server:
  port: 8085

  tomcat:
    uri-encoding: utf-8

  servlet:
    session:
      timeout: 30m

spring:

  application:
    name: kafka-producer

  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password:
      initial-size: 1
      max-active: 30
      min-idle: 1
      max-wait: 30000

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      #批量发送量
      batch-size: 16
      #发送失败重试次数
      retries: 0
      #批量缓存区
      buffer-memory: 33554432
      #序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    listener:
      missing-topics-fatal: false
