server:
  port: 8083

  tomcat:
    uri-encoding: utf-8

  servlet:
    session:
      timeout: 30m

spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password:
      initial-size: 1
      max-active: 30
      min-idle: 1
      max-wait: 30000

  application:
    name: guava

  profiles:
    active: dev
