server:
  port: 8084

  tomcat:
    uri-encoding: utf-8

  servlet:
    session:
      timeout: 30m

spring:

  application:
    name: zookeeper

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password:
      initial-size: 1
      max-active: 30
      min-idle: 1
      max-wait: 30000

  profiles:
    active: dev

zookeeper:
  url: 127.0.0.1:2181
  timeout: 4000
  retries: 3
  baseSleepTimeMs : 1000