server:
  port: 8085

  tomcat:
    uri-encoding: utf-8

  servlet:
    session:
      timeout: 30m

spring:

  application:
    name: redis

  profiles:
    active: dev

  redis:
    sentinel:
      nodes: redis://127.0.0.1:26379,redis://127.0.0.1:26380
      master: mymaster
    password:
    database: 16
    # 将themilef的默认缓存禁用，热加载生效
    thymeleaf:
      cache: false
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0

redisson:
  address: redis://127.0.0.1:6379